from config import GenerationMode


class ModelFactory:
    def new(config):
        if config['generation_mode'] == GenerationMode.AUTO:
            return AutoGeneratedModel(config)
        elif config['generation_mode'] == GenerationMode.MANUAL:
            return ManuallyGeneratedModel(config)
        else:
            raise Exception("no other generation type yet implemented")


class ModelInterface:
    def __init__(self, config):
        pass

    def start(self):
        pass

    def update(self):
        pass

    def pause(self):
        pass

    def resume(self):
        pass

    def shutdown(self):
        pass


class AutoGeneratedModel (ModelInterface):
    def __init__(self, config):
        super().__init__(config)

    def start(self):
        return super().start()

    def update(self):
        return super().update()

    def pause(self):
        return super().pause()

    def resume(self):
        return super().resume()

    def shutdown(self):
        return super().shutdown()


class ManuallyGeneratedModel(ModelInterface):
    def __init__(self, config):
        super().__init__(config)
