from model.auto_generated_model import AutoGeneratedModel
from model.manually_generaed_model import ManuallyGeneratedModel
from config import GenerationMode

class ModelBuilder:
    def new_simulation(config):
        if config['generation_mode'] == GenerationMode.AUTO:
            return AutoGeneratedModel(config)
        elif config['generation_mode'] == GenerationMode.MANUAL:
            return ManuallyGeneratedModel(config)
        else:
            raise NotImplementedError()
